version: 0.1

environment_variables:
  plaintext:
    PACKER_NO_COLOR: "1"
    PACKER_LOG: "1"

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
      - unzip packer_0.12.0_linux_amd64.zip
  build:
    commands:
      - ./packer build "packer.json"
